refresh_interval: 5m0s
server_port: 8777
providers:
    kimi:
        enabled: true
        cookies:
            kimi.com:
                kimi-auth: ${KIMI_AUTH_TOKEN}
    zai:
        enabled: true
        api_key: ${ZAI_API_KEY}
    codex:
        enabled: false
        oauth:
            token_file: ${HOME}/.codex/auth.json
    claude:
        enabled: false
        cookies:
            claude.ai:
                sessionKey: ${CLAUDE_SESSION_KEY}
